# Node.js with React - Azure Pipeline
# Pipeline for a Node.js project using a MERN stack with React
# Includes steps for building, running tests, and analyzing code with SonarQube

trigger:
- develop

pool: TestAgent

steps:
# Step 1: Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Step 2: Run backend tests with Mocha and Chai
- script: |
    cd backend
    dir
    npm install
    npm run test
  displayName: 'Run backend tests with Mocha and Chai'
  continueOnError: false

# Step 4: Publish backend test results
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/backend/test-*.xml'
    failTaskOnFailedTests: true
    failTaskOnFailureToPublishResults: true
    failTaskOnMissingResultsFile: true
    testRunTitle: 'Publish Test Results'

# Step 2: Run frontend tests with Jest
- script: |
    cd frontend
    npm install
    npm test
  displayName: 'Run frontend tests with Jest'
  continueOnError: false