version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
      - SECRET=${SECRET}
